import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import LayoutContent from "./LayoutContent"; // Novo arquivo que cuidará do layout e da sessão
import { PacienteProvider } from "@/context/PacienteContext";
import Providers from "./providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata: Metadata = {
  title: "Vivere web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //<AuthProvider>
    <Providers>

      <PacienteProvider>

        <html lang="pt-br" className="light">
          <body className={inter.className}>
            <LayoutContent>{children}</LayoutContent>
            <Toaster />
          </body>
        </html>

      </PacienteProvider>

    </Providers>

    //</AuthProvider>
  );
}
