import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Header } from "@/components/header";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata: Metadata = {
  title: "Vivere web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light">
      <body className={inter.className}>
        <Sidebar />
        {/* <Header /> */}
        <main className="mx-5 mt-16 sm:ml-[300px] sm:mt-3">
          {children}
        </main>
      </body>
    </html>
  );
}
